/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Kullanici as PrismaKullanici } from "@prisma/client";

export class KullaniciServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.KullaniciCountArgs, "select">
  ): Promise<number> {
    return this.prisma.kullanici.count(args);
  }

  async kullanicis<T extends Prisma.KullaniciFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.KullaniciFindManyArgs>
  ): Promise<PrismaKullanici[]> {
    return this.prisma.kullanici.findMany<Prisma.KullaniciFindManyArgs>(args);
  }
  async kullanici<T extends Prisma.KullaniciFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.KullaniciFindUniqueArgs>
  ): Promise<PrismaKullanici | null> {
    return this.prisma.kullanici.findUnique(args);
  }
  async createKullanici<T extends Prisma.KullaniciCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.KullaniciCreateArgs>
  ): Promise<PrismaKullanici> {
    return this.prisma.kullanici.create<T>(args);
  }
  async updateKullanici<T extends Prisma.KullaniciUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.KullaniciUpdateArgs>
  ): Promise<PrismaKullanici> {
    return this.prisma.kullanici.update<T>(args);
  }
  async deleteKullanici<T extends Prisma.KullaniciDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.KullaniciDeleteArgs>
  ): Promise<PrismaKullanici> {
    return this.prisma.kullanici.delete(args);
  }
}
